Large refactoring

diff --git a/template/script.sh.erb b/template/script.sh.erb
--- a/template/script.sh.erb
+++ b/template/script.sh.erb
@@ -5,11 +5,6 @@
 
 set -x
 
-# Benchmark info
-echo "TIMING - Starting main script at: $(date)"
-
-echo "Starting up rserver..."
-
 # Function get_available_port only used for local testing
 # i.e. without the pre-defined functions available from OOD
 get_available_port()
@@ -22,11 +17,15 @@ get_available_port()
   echo $port
 }
 
+# Benchmark info
+echo "TIMING - Starting main script at: $(date)"
+
+[ -z "$RSTUDIO_SERVER_IMAGE" ] && echo "Missing \$RSTUDIO_SERVER_IMAGE" && exit 1
+
 if [ "$1" = "debug" ]; then
   port="$(get_available_port)"
 fi
 
-IMAGE=/apps/containers/R/RStudio-Server-R-4.1.3-TensorFlow-2.4.2.sif
 EXEC=/usr/lib/rstudio-server/bin/rserver
 
 HOST_WORKING_DIR="$TMPDIR/rstudio-server-PID-$$"
@@ -37,7 +36,7 @@ SERVER_DATA_DIR="$SERVER_WORKING_DIR"
 SECURE_COOKIE_KEY_FILE="$SERVER_WORKING_DIR/secure-cookie-key"
 SERVER_DB_DIR="$SERVER_WORKING_DIR"
 SERVER_DB_CONFIG_FILE="$SERVER_DB_DIR/database.conf"
-SERVER_PORT=$port
+SERVER_PORT="$port"
 
 HOST_AUTH_PAM_HELPER_SCRIPT="/apps/staff/rstudio-server-auth"
 AUTH_PAM_HELPER_SCRIPT=/rstudio-server-auth
@@ -52,30 +51,41 @@ provider=sqlite
 directory=$SERVER_DB_DIR
 EOF
 
-RCMD="$EXEC"
-RCMD+=" --server-user=$USER"
-RCMD+=" --server-daemonize=0"
-RCMD+=" --www-port=$SERVER_PORT"
-RCMD+=" --server-working-dir=$SERVER_WORKING_DIR"
-RCMD+=" --server-data-dir=$SERVER_DATA_DIR"
-RCMD+=" --secure-cookie-key-file=$SECURE_COOKIE_KEY_FILE"
-RCMD+=" --database-config-file=$SERVER_DB_CONFIG_FILE"
-RCMD+=" --auth-none=0"
-RCMD+=" --auth-pam-helper-path=$AUTH_PAM_HELPER_SCRIPT"
-RCMD+=" --auth-encrypt-password=0"
-
 if [ "$1" = "debug" ]; then
   echo "STARTING rstudio-server IN $HOST_WORKING_DIR"
   echo "Listening on $SERVER_PORT"
-  echo "$RCMD" | tr ' ' '\n'
-  CMD=bash
-else
-  CMD="$RCMD"
 fi
 
-echo "## Container output ##"
+# Generate an `rsession` wrapper script
+export RSESSION_WRAPPER_FILE="${HOST_WORKING_DIR}/rsession.sh"
+(
+umask 077
+sed 's/^ \{2\}//' > "${RSESSION_WRAPPER_FILE}" << EOL
+  #!/usr/bin/env bash
+  # Log all output from this script
+  export RSESSION_LOG_FILE="${SERVER_WORKING_DIR}/rsession.log"
+  exec &>>"\${RSESSION_LOG_FILE}"
+  echo "Launching rsession..."
+  set -x
+  exec /usr/lib/rstudio-server/bin/rsession --r-libs-user "${R_LIBS_USER}" "\${@}"
+EOL
+)
+chmod 700 "${RSESSION_WRAPPER_FILE}"
+
 singularity exec \
   -B "$HOST_AUTH_PAM_HELPER_SCRIPT":$AUTH_PAM_HELPER_SCRIPT \
   -B "$HOST_WORKING_DIR":"$SERVER_WORKING_DIR" \
   --env "RSTUDIO_PASSWORD=$RSTUDIO_PASSWORD" \
-  "$IMAGE" $CMD
+  "$RSTUDIO_SERVER_IMAGE" \
+  "$EXEC" \
+  --server-user=$USER \
+  --server-daemonize=0 \
+  --www-port=$SERVER_PORT \
+  --server-working-dir=$SERVER_WORKING_DIR \
+  --server-data-dir=$SERVER_DATA_DIR \
+  --secure-cookie-key-file=$SECURE_COOKIE_KEY_FILE \
+  --database-config-file=$SERVER_DB_CONFIG_FILE \
+  --auth-none=0 \
+  --auth-pam-helper-path=$AUTH_PAM_HELPER_SCRIPT \
+  --auth-encrypt-password=0 \
+  --rsession-path=$SERVER_WORKING_DIR/rsession.sh
